const testimonials = [
    {
      name: "Donald Trump",
      quote:
        "Priced In transformed my trading strategy. Their insights are incredible!",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Nancy Pelosi",
      quote: "Trade like your congresswoman. Highly recommend!",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Gordon Ramsay",
      quote: "Finally, a tool that isn't RAW!",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Shrek",
      quote: "It’s like an onion. So many layers of insight.",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Tony Stark",
      quote: "Even JARVIS couldn’t predict markets this well.",
      stars: "★★★★★",
      level: "Quant",
    },
    {
      name: "Batman",
      quote: "Even Gotham's market volatility couldn’t shake PricedIn.",
      stars: "★★★★★",
      level: "Quant",
    },
    {
      name: "SpongeBob SquarePants",
      quote: "I’m ready, I’m ready… to trade, thanks to PricedIn!",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Dwight Schrute",
      quote: "Fact: Priced In increased my alpha by 400%.",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Michael Scott",
      quote: "PricedIn is the Michael Jordan of trading apps.",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Darth Vader",
      quote: "Impressive. Most impressive.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Buzz Lightyear",
      quote: "To the profits and beyond!",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Gollum",
      quote: "My precious... portfolio.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Sheldon Cooper",
      quote: "PricedIn is statistically significant and emotionally satisfying.",
      stars: "★★★★★",
      level: "Quant",
    },
    {
      name: "Rick Sanchez",
      quote: "Wubba Lubba Dub Dub! PricedIn's insights are interdimensional.",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Oprah Winfrey",
      quote: "You get a trade! You get a trade!",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Kim Kardashian",
      quote: "I don’t check the market… I check Priced In.",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Thanos",
      quote: "Perfectly balanced, as all portfolios should be.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Bob Ross",
      quote: "There are no mistakes with PricedIn. Only happy trades.",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Peppa Pig",
      quote: "Oink if you love profits!",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Steve Jobs",
      quote: "Insanely great. Just like my wardrobe.",
      stars: "★★★★★",
      level: "Quant",
    },
    {
      name: "Elmo",
      quote: "Elmo made money using PricedIn!",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Kanye West",
      quote: "Priced In is the best trading tool of all time.",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Ted Lasso",
      quote: "Believe in your trades - and PricedIn.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Gru",
      quote: "PricedIn is despicably good.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Barack Obama",
      quote: "Let me be clear. PricedIn works. It works remarkably well.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Zuckerberg",
      quote: "I taught Meta how to trade using PricedIn.",
      stars: "★★★★★",
      level: "Quant",
    },
    {
      name: "Joe Rogan",
      quote: "PricedIn is wild. You’ve gotta try this out.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Will Smith",
      quote: "PricedIn keeps my profits in check!",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Taylor Swift",
      quote: "I’m trading all my bad stocks for good ones using PricedIn!",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Harry Styles",
      quote: "PricedIn is golden. Just like my trades.",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Keanu Reeves",
      quote: "Breathtaking insights.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Mr. Beast",
      quote: "I'm giving $10,000 to everyone using PricedIn.",
      stars: "★★★★★",
      level: "Intermediate",
    },
    {
      name: "Mark Cuban",
      quote: "I’m in. 100% equity.",
      stars: "★★★★★",
      level: "Quant",
    },
    {
      name: "Tyler Durden",
      quote: "First rule of investing - use Priced In.",
      stars: "★★★★★",
      level: "Expert",
    },
    {
      name: "Kermit the Frog",
      quote:
        "It’s not easy being green… except in profits if you're using PricedIn!",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Jon Snow",
      quote: "I know nothing… but Priced In helps.",
      stars: "★★★★★",
      level: "Beginner",
    },
    {
      name: "Iron Man AI",
      quote: "Backtested. Optimized. Profitable. PricedIn.",
      stars: "★★★★★",
      level: "Expert",
    },
  ];

export default testimonials